# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://weixinbing.top
date_format: "ordinal"
title: Bing's Blog
subtitle: "魏心兵的个人博客"
description: "魏心兵的个人博客，公众号：进击的程序员"
keywords: Bing, Xinbing Wei, bingstyle, weixinbing, 进击的程序员
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: weixinbing
organization: 
organization_url: 
github_username: weixinbing
location: Chengdu, China
email: weixinbingcn@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页
  -
    href: /categories/
    label: 分类
  -
    href: /wiki/
    label: 维基
  -
    href: /links/
    label: 链接
  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
highlighter: rouge
markdown: kramdown

kramdown:
  input:            GFM
  hard_wrap: true
  auto_id_prefix:   ''
  auto_ids:         true
  extensions:
    - autolink
    - footnotes
    - smart
  transliterated_header_ids: false
  footnote_nr:   1
  entity_output: as_char
  toc_levels:    1..6
  smart_quotes:  lsquo,rsquo,ldquo,rdquo
  use_coderay:   true

  # coderay:
  #   coderay_wrap:              div
  #   coderay_line_numbers:      inline
  #   coderay_line_number_start: 1
  #   coderay_tab_width:         2
  #   coderay_bold_every:        10
  #   coderay_css:               style

paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: weixinbing/weixinbing.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: 
    repo: blog-comments
    oauth:
        client_id: 
        client_secret: 
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: weixinbing
    repo: blog-comments
    clientID: d279715345e5075875e6
    clientSecret: eb58fc3174bead3dc6d01d3216dea9b3caee71a1
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#      Google      #
# ---------------- #
google:
    analytics_id: UA-164920916-1
    adsense:
        footer: false
        sidebar: false 
        content_header: false
        content_footer: false
